### ISSUE TITLE
SQL restore failed

### ISSUE THREAD

**Issue by Craig-IAS** [infiniteautomation/ma-modules-public#77] opened 2019-11-06 10:14 UTC
**Describe the bug**
When doing  SQL restore.  The response shows that the restore failed. 
![Screen Shot 2019-11-06 at 12 13 49](https://user-images.githubusercontent.com/47353996/68289543-fab8ea00-008e-11ea-8798-588fa3f414b6.png)

 If I look at the ma.log file it shows that the restore was successful. 
This was done on an instance running MySQL

**To Reproduce**
Steps to reproduce the behaviour:
In v3 mangu UI go to  /ui/administration/system/sql-backup
choose a backup file and click restore database

**Expected behaviour**
API response to match ma.log file entry

**Screenshots**

**Mango Version (please complete the following information):**
 - Core Version: [e.g. 3.5.5]
 - API Version [e.g. 3.6.4]

**Additional context**
`API response:
{resourceId: "SYSACTION_18eb08e5-ddc8-4e9f-8aa6-f0307ca0291d",…}
expires: 1573035081617
finished: true
queueSize: 0
resourceId: "SYSACTION_18eb08e5-ddc8-4e9f-8aa6-f0307ca0291d"
results: {completeBeforeCancel: false,…}
cancelled: false
completeBeforeCancel: false
failed: true
finished: true
messages: [{level: "error", genericMessage: "Database restored", contextKey: null, contextualMessage: null}]
taskId: "TR_SYSACTION_18eb08e5-ddc8-4e9f-8aa6-f0307ca0291d"
threadName: "Temporary Resource Timeout for : SYSACTION_18eb08e5-ddc8-4e9f-8aa6-f0307ca0291d"`

**ma.log Snippet**
`INFO  2019-11-06T10:01:21,617 (com.serotonin.m2m2.rt.maint.work.DatabaseBackupWorkItem.restore:319) - Attempting to restore database backup from: /opt/mango/backup/core-database-MYSQL-Nov-05-2019_112209.zip 
INFO  2019-11-06T10:01:29,549 (com.serotonin.m2m2.rt.maint.work.DatabaseBackupWorkItem.restoreMysqlToDatabase:513) - Backup restored successfully formango in localhost:3306 `

**Comment by terrypacker** [comment] 2019-11-06 12:07
@jazdw this is due to the temporary resource timing out.  I think the solution is to increase the timeout when creating the resource request.  This would be a UI change.  Agree?

**Comment by terrypacker** [comment] 2020-02-24 19:58
I just tested this by trying to restore a missing file, the error is logged in the console but the request sent back to the page did not have any error information in it.  Review the backend code.

**Comment by terrypacker** [comment] 2020-02-25 20:40
I have fixed up the feedback from the endpoint such that it returns a message for backup files not found.  The UI needs to use this message and display it as a failure message underneath the select a file to restore and restore database button row.

To reproduce open the restore sql page and select a backup to restore to.  Then go to your file system and rename the file/delete it.  Then click Restore Database and see the response in dev tools.

Here is the JSON response
```
{
  "resourceId" : "SYSACTION_29f5fa02-11e5-40f7-b138-68589dce5de1",
  "results" : {
    "completeBeforeCancel" : false,
    "messages" : [ {
      "level" : "error",
      "genericMessage" : "Database backup not found at: /Users/tpacker/Work/IAS/development/mango/git/infiniteautomation/ma-core-public/Core/backup/core-database-H2-Feb-13-2020_160850.zip",
      "contextKey" : null,
      "contextualMessage" : null
    } ],
    "cancelled" : false,
    "finished" : true,
    "failed" : true
  },
  "finished" : true,
  "threadName" : "Temporary Resource Timeout for : SYSACTION_29f5fa02-11e5-40f7-b138-68589dce5de1",
  "taskId" : "TR_SYSACTION_29f5fa02-11e5-40f7-b138-68589dce5de1",
  "expires" : 1582663626197,
  "queueSize" : 0
}
```

**Comment by terrypacker** [comment] 2020-03-03 20:58
Closing as fixed.

**Closed by terrypacker** 2020-03-03 20:58 UTC
